#cloud-config

groups:
  - mc

users:
  - name: minecraft
    shell: /usr/sbin/nologin
    groups: mc
  - name: nia
    groups: sudo, mc, docker
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_import_id:
      - "gh:ntatrishvili"
  - name: luka
    groups: sudo, mc, docker
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_import_id:
      - "gh:dr-mato"
  - name: samer
    groups: sudo, mc, docker
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_import_id:
      - "gh:samerbahri98"

package_update: true
package_upgrade: true
packages:
  - git
  - make
  - zip

runcmd:
  - ["git","clone","https://github.com/ntatrishvili/minecraft_server.git","/minecraft"]
  - ["wget", "https://piston-data.mojang.com/v1/objects/84194a2f286ef7c14ed7ce0090dba59902951553/server.jar",
    "-O", "/minecraft/app/server.jar"]
  - ["chown", "-R", "nia:mc", "/minecraft"]
  - ["chmod", "-R", "g=u", "/minecraft"]
# Install Minio Client
  - ["wget", "https://dl.min.io/client/mc/release/linux-amd64/mc", "-O", "/usr/bin/mc"]
  - ["chmod", "755", "/usr/bin/mc"]
